version: "3.7"

services:
    # Database
    my-db: 
        image: mongo:5
        ports:
            - 27017:27017
        environment:
            - TZ=Asia/Seoul

    # Express
    my-express:
        # Dockerfile 설정
        build:
            # Dockerfile의 위치
            context: . 
        
        # Container Port 연결
        #   - host:container
        ports:
            - 3000:3000
        
        # Volume Mount
        #   - host:container
        volumes:
            - ./src:/app/src

            - ./index.js:/app/index.js

            - ./package.json:/app/package.json
            - ./yarn.lock:/app/yarn.lock
            - ./.env:/app/.env

            - /app/node_modules

        # 환경 변수 설정
        # environment:
        #     - TZ=Asia/Seoul
        env_file: .env

        # 재시작 설정
        restart: always
